AttributeError: 'ImageClip' object has no attribute 'set_position'. Did you mean: 'with_position'?
Okay, the error AttributeError: 'ImageClip' object has no attribute 'set_position'. Did you mean: 'with_position'? indicates that the method set_position has been changed to with_position in the version of moviepy you are using.

Here's the corrected code, incorporating the change from set_position to with_position, also changing set_opacity to with_opacity: